# 7.- Arreglos con NUMPY

En este capítulo aprenderás a utilizar algunas cualidades básicas de NumPy (Numerical Python).
NumPy es una de las librerías más populares de Python, ya que puede procesar listas de múltiples
dimensiones

## 7.2.- Arreglo de Datos

Como en la sección anterior, invocaremos a la librería NumPy como np

In [1]:
import numpy as np


Armemos un arreglo de todos los factoriales del 1 al 6

In [2]:
factoriales = np.array([1,2,6,24,120,720])

Verifica el tipo de objeto que generamos

In [5]:
type(factoriales)
print(factoriales)


[  1   2   6  24 120 720]


La función array copia automáticamente las dimensiones del argumento. Por ejemplo, el siguiente arreglo (array) está formado por tres filas y dos columnas.

In [7]:
np.array([[3,4],[6,7],[10,11]])

array([[ 3,  4],
       [ 6,  7],
       [10, 11]])

#### Por tu cuenta

Arma un arreglo de una dimensión desde una compresnidón de lista que produce todos los números nones del 1 al 30

In [9]:
non = np.array([x for x in range(1,31) if x %2 != 0])
print(non)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


### 7.2.2 - Atributos de Arreglos

En esta sección usaremos los siguientes 2 arreglos

enteros = np.array([[9,10,11,12],[8,7,6,5]])

flotantes=np.array([[9**(1/2),10**(1/2),3.33,],[10/3,3.4,3.03]])

In [10]:
enteros = np.array([[9,10,11,12],[8,7,6,5]])
flotantes = np.array([[9**(1/2),10**(1/2),3.33,],[10/3,3.4,3.03]])

Checa el tipo de elemento con dtype

In [14]:
enteros.dtype


dtype('int64')

In [16]:
flotantes.dtype

dtype('float64')

Revisa que puedes ver dimensione con ndim y forma con shape del arreglo

In [17]:
enteros.ndim

2

In [20]:
flotantes.ndim
enteros.shape
flotantes.shape

(2, 3)

Size y itemsize te permite conocer el numero de elemntos y de bytes para almacenar

In [21]:
enteros.size
enteros.itemsize
flotantes.size
flotantes.itemsize

8

Se puede iterar facilmente a través de un arreglo

In [22]:
for filas in flotantes:
    for columna in filas:
        print(columna,end = " ")
    print()

3.0 3.1622776601683795 3.33 
3.3333333333333335 3.4 3.03 


#### Por tu cuenta

Para el arreglo que armaste en el "Por tu cuenta" previo, checa el numero de dmiensiones y forma del arreglo

In [23]:
non.ndim

1

In [24]:
non.dtype

dtype('int64')

### 7.2.3 - Creando Arreglos desde Rangos

La función arange (una sola R!!!!) nos permite crear rangos de enteros. Crea:

- Un arreglo del 0 al 7
- Un arreglo del 3 al 7
- Un arreglo del 12 al 2 en pasos de 3 en 3 (si, en orden inverso)

In [25]:
import numpy as np

In [26]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [28]:
np.arange(12,2,-3)

array([12,  9,  6,  3])

Tambien se pueden usar tamaños de paso no enteros. Crea un arreglo con linspace de 0 al 1 que vaya de .25 en .25

In [29]:
np.linspace(0.0,1.0,num = 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Y se puede cambiar la forma del arreglo con reshape. Crea un arreglo con arange que vaya del 21 al 1 en orden inverso, y luego dale forma de matriz de 4x5

In [30]:
np.arange(21,1,-1).reshape(4,5)

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

Checate que si el arreglo tiene 1000 o más elementos, numpy no muestra la totalidad de los datos. Generaun arreglo de 0 a 9999 y dale forma de 5 x 2000

In [31]:
np.arange(0,10000).reshape(5,2000)

array([[   0,    1,    2, ..., 1997, 1998, 1999],
       [2000, 2001, 2002, ..., 3997, 3998, 3999],
       [4000, 4001, 4002, ..., 5997, 5998, 5999],
       [6000, 6001, 6002, ..., 7997, 7998, 7999],
       [8000, 8001, 8002, ..., 9997, 9998, 9999]], shape=(5, 2000))

#### Por tu cuenta

Usa la función arange para crear una rreglo de 20 enteros pares del 42 al 80, y luego rearmalo en una matriz de 4x5

In [33]:
np.arange(42,81,2).reshape(4,5)

array([[42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80]])

### 7.2.4 - ¿Que tan más rapido es un arreglo?

Usa la magia %timeit y la librería random para crear una comprensión de lista que simule un tiro de dao 6000000 de veces y medir su tiempo

In [2]:
import random
%timeit [random.randint(1, 6) for _ in range(6000000)]

KeyboardInterrupt: 

Ahora usa %timeit para medir el tiempo de un tiro de dado 6000000 de veces pero hecho con arreglo

#### Por tu cuenta

Usa %timeit para ver que es mas rapido - una lista que sume todos los enteros del 0 al 9 999 999 o un arreglo que haga lo mismo con el metodo sum

## 7.3.- Operaciones con Arreglos

Arma un arreglo de todos los pares del 2 al 15.

- Sumale 1 al arreglo
- Multiplicalo por 3
- Sacale raiz cuadrada

In [5]:
import numpy as np
pares = np.arange(2,15,2)

In [6]:
pares +1

array([ 3,  5,  7,  9, 11, 13, 15])

In [7]:
pares * 3

array([ 6, 12, 18, 24, 30, 36, 42])

In [8]:
pares **(1/2)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739])

Al mismo arreglo, aplicale un +=10

Arma un arreglo (lista1) que vaya del 2 al 18 de 3 en 3, y otro arreglo (lista2) usando linspace que vaya del -2 al 20 dividido en 6 numeros

- Resta lista1 de lista2
- divide lista2 entre lista1

También puedes comparar los arreglos

#### Por tu cuenta

Crea un arreglo de los valores que vayan del 1 al 5, y luego elvealo al cuadrado usando **

### 7.3.2.- Métodos de Cálculo

Considera el siguiente arreglo 

ventas=np.array( [[554,606,710,851],[1244,898,416,1763],
 [841,655,1105,1067]])


Podemos usar métodos para calcular la sum, min, max, mean, std, var. 

También es posible hacerlo por filas y columnas. Checa como se hace con axis = 1 y 0

#### Por tu cuenta

Usa el generador de numeros aleatoreos de numpy (np.random.randint) para crear una rreglo de 12 calificaciones aleatorias del 60 al 100, y luego dale forma en una matriz de 3x4. Calcula el promedio de todas las calificaciones, el promedio de cada columna y de cada fila. 

## 7.4.- Indexando y Cortando arreglos

Crea el arreglo

ventas=np.array ([[ 554, 606, 710, 851],
 [1244, 898, 416, 1763],
 [ 841, 655, 1105, 1067]])
 
 - Selecciona el item 2,1
 - Selecciona el item 1,3
 - Selecciona la fila 1

Solicita las filas con índices 0 y 1

Ahora para solicitar las filas con indices 1 y 2

Quieres solo los elementos de la primera columna?

Que la las columnas con indices 0 y 2?

#### Por tu cuenta

Dado el siguiente arreglo

array([[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]])

- Selecciona la segunda fila
- Selecciona la primera y tercera fila
- Selecciona las tres columnas de enmedio

### 7.4.2.- Transponer

Con **reshape** puedes producir una copia superficial del arreglo con una nueva dimension. 

ventas = np.array([[ 500, 600, 550, 800],
 [1200, 800, 400,1000]])

Usa el arreglo anterior para darle dimension de 1x8

El metodo **resize** modifica la forma del original (no crea copia)

Y **transpose** rapidamente le da la vuelta a filas y columnas, este se hace aplicando el atributo T, que no modifica el original, solo una vista.

## 7.5.- Pandas - Series

Vamos a usar estos datos para Series - tiempo_web = pd.Series([160,256,98,108])

Este es el tiempo que invierten en videojuegos 4 estudiantes

Para crear una serie con el mismo elemento

Acceder a un elemento es facil

Series tiene acceso a los mismos metodos que arreglos para estadistica descriptiva

Tambien, todo esto se puede resumir con **describe**

También podemos personalizar los indices de series a traves de index

['Laura','Daniel','Alberto','Eva'] 

Asigna esos nombres

O puedes usar un diccionario para eso:

Puedes llamar a los elementos personalizados

Tambien se pueden llamar como atributos

#### Por tu cuenta

Usa el generador aleatorio de NumPy (np.random.randint) para generar 6 calificaciones del 60 al 100 y guardarlos en una serie. 

A continuación arma las siguientes tareas:

- Convierte el arreglo en una serie llamada calificacion
- Determina la min, max y promedio
- Produce TODAS las estadisticas descriptivas

## 7.6.- Pandas - DataFrames

##### Crear un Dataframe de un diccionario

Agarra este diccionario y conviertelo en un dataframe

 reg_peso = {'Vanesa':[68,67,66,65],'Kevin':[89,89,90,88],
 'Fernanda':[59,60,60,62],'Patricia':[70,68,67,65]}

##### El atributo Index

Añade los siguientes indices personalizados

peso.index = ['Mes 1','Mes 2','Mes 3','Mes 4']

##### Accesar Columnas

Selecciona la información de Fernanda

Selecciona la de Patricia pero como atributo

##### Loc y iloc

Selecciona la información del Mes1 usando Loc

Ahora solo la fila 1 usando iloc

Ahora del Mes 1 al Mes 3 usando loc

Saca filas especificas (mes 1 y 3) usando loc

Y ahora los Meses 2 y 3 de Vanesa y Patricia solamente con loc

##### Indices Booleanos

Dime los pesos mayores a 70kg en la tabla

Y ahora los pesos mayores a 65kg y menores a 80kg

##### Accesar una celda especifica de un Dataframe

Que pasa si solo queremos cuanto pesaba Patricia en el mes 3? Usa at

Resulta que Kevin en realidad pesaba 85kg en el mes 4, cambia su valor usando at

##### Estádistica descriptiva

Puedes usar el metodo **Describe** para sacar todas las estadisticas del dataframe

También puedes cambiar la cantidad de decimales usando **Precision**

Y también se pueden aplicar los metodos de estadistica descriptiva individuales como mean

##### Transponer

Si quisieramos voltear el dataframe, tendríamos que hacer el método T

Y ahora eso nos ayudaría a sacar los estadísticos para los meses en vez de para las personas

Y el peso promedio por mes de nuestra gente

##### Ordenar el Dataframe

Ahora vamos a arreglar el dataframe por fila, con los indices en orden descendente

Las columnas en orden ascendente

Y también se vale ordenar los valores según una fila o columna especifica.  El siguiente código ordena de forma descendente los datos del DataFrame con respecto
a los valores del Mes 1.